### ISSUE TITLE
Map Load

### ISSUE THREAD

**Issue by jesramos** [BE3dARt/ARMA-3-ARTILLERY-CALCULATOR-ARES#1]
I liked your project, however when opening ARES-Arma 3-Online-Artillery-Calculator.html the map does not load

**Comment by BE3dARt** [comment]
Hey! :) I've never had someone commented on a project of mine, so I am quite new to this. I hope everything works now! I have some uncommited stuff like a calculator for MAAWS :D. You can test the live website at https://be3dart.ch/ARES-Arma3-Online-Artillery-Calculator.html

**Comment by BE3dARt** [comment]
Oh, It may be that you don't have the icon. :/ I almost have a working version without the need of icons as markers, but I was quite busy lately.

**Comment by jesramos** [comment]
It is very well done, it is difficult to find something like this on the internet

**Comment by BE3dARt** [comment]
I figured it would be best if I update the readme soon, make a small tutorial and explain what means what. Thank you very much!

**Comment by jesramos** [comment]
I have a project similar to yours here that I found on github once, but the owner left it hidden and you can't access it. I'll attach it, who knows, you can modify something with yours
[FATDS-main - Copia.zip](https://github.com/BE3dARt/ARMA-3-ARTILLERY-CALCULATOR-ARES/files/6252437/FATDS-main.-.Copia.zip)

**Comment by BE3dARt** [comment]
Wow! Thank you very much! Do you intend to modify it, or just use it? You could suggest some things I need to implement if you want.
I also have to check in which state this project is, I am not sure if the last commit is a working version, I'll have to look through it.

**Comment by jesramos** [comment]
I'm not very good at programming, I end up looking for some projects on github and using.

**Comment by jesramos** [comment]
yours is very simple to use, you just need to mark it on the map. since what I sent is necessary to mark the GRID and other information

**Comment by BE3dARt** [comment]
At the moment there is an issue with the marker in the GitHub version. The live version on my website is fine. I don't think I understand your second sentence correctly: What do you mean by "GRID and other information"?

**Comment by jesramos** [comment]
Well, GRIND and other information is from the project I was using before I found yours. I'll leave a screenshot for you to understand better.
![align_target](https://user-images.githubusercontent.com/81809570/113573823-44de2c00-95f1-11eb-85f2-b794933096c3.JPG)
however, for better accuracy it is necessary to add the 8 digits of the grid, Arma 3 provides us with a 6-digit grid using the map.  
with that every time I was going to change my position in KOTH I had to find the 8-digit grid.

**Comment by BE3dARt** [comment]
Ah, I think I understand what you mean, sorry, swiss-german / german is my main language. 

**Precision**
I mapped the coordinate system of Arma III into Leaflet JS. Every grid-square is 100 meters high and wide. So, the precision is down to 1 meter.
The altitude data is exported from Arma III directly, as you can see here when calling my API https://api.be3dart.ch/ARES.php?x=11000&y=10000, the precision of altitude is millimeters.
I don't think you need it more precise than that? Or do you?

**ML Elevation**
Do you know what the "ML Elevation" signifies on that screenshot? Maybe it's the same as I tried to do: On my map, the second value "Exp. " stands for experimental, because I was trying to erase the error you get when not being on completely flat ground. BUT, I figured, because in KOTH you get the real elevation value displayed at the bottom, I wouldn't need to calculate the error when only playing KOTH. 
Because of that error calculation, the Azimuth is sometimes wrong in the GitHub version..., on the live version, it should be correct.

Btw, as you noticed, you can just drag the markers around, you don't need to create a new one every time.

**Comment by BE3dARt** [comment]
At the moment I am very busy because it's my final year in the Swiss equivalent of college. I can spare some time, but only a limited amount. If you would like to contribute or suggest some features, just send me a message. 

You said: "I'm not very good at programming", everything you see here I have learned by myself. You can do that too if you want! I suggest just playing around, you can even use this project. GitHub has a cool service called GitHub pages where you can host your own website which displays the content of your repository on GitHub. I started like that as well!

If you've developed some stuff and you would like to share it to contribute to this project, tell me, and I'll set up a way you can commit to this repository.

**Comment by jesramos** [comment]
English doesn't belong to me either. PT-BR is my native language.
If I have any suggestions I'll be telling you. =)
